# -*- coding: utf-8 -*-
"""greeting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CxvNGWa7M_eNXiYwFuudvlI_MyEWwp1
"""

import streamlit as st

st.title("مرحبا بكم ")
name = st.text_input("ادخل الاسم : ")

if name :
  st.write("اهلا يا " , name )
  st.balloons()